### ISSUE TITLE
Volume based commands fail due to m_RX_V3900_family check

### ISSUE THREAD

**Issue by ellisch99** [a-lurker/Vera-Plugin-Yamaha-RX-HTTP#1]
I have found that on my RX-V2075 that the volume commands would fail. Investigation found that this was due to m_RX_V3900_family being set to true even though my Reciever uses "Volume" not "Vol".
The reason is that the getZoneStatus gets called for each zones and for some of those zones the "Volume" tag does not exist in the XML meaning m_RX_V3900_family gets set to true.

Suggested fix is to create new Variable "VolumeTag" within Device to store the tag that should be used and refer to that when creating or searching XML strings. This could be defaulted to "Volume" and the help files explain the RX_V3900_family scenario so users can set to "Vol" if they wish.

I'm new to LUA but got a fix in my system working so let me know if you want me to have a go at this.

**Comment by a-lurker** [comment]
Sorry for the delay. I've now modified the L_YamahaRxHTTP1.lua to version 0.56   You just need to update that file and restart everything. You didn't mention what zone could not be controlled? In other AVR's it's Zone 4. The mobile app generally shows that zone can't be controlled.

Have a look at this as well:
[Vera forum](https://community.getvera.com/t/yamaha-network-control-plugin-using-http/179363/46?u=a-lurker)

**Comment by ellisch99** [comment]
It was the main zone. As mentioned on my system getZoneStatus seems to get called multiple times. I assume for each zone 1 to 4. Now for some reason some of those zones return XML that does not contain a "Volume" tag so the code sets the global variable m_RX_V3900_family to True so the next volume call will not not work as the code is now looking for "Vol" instead of "Volume"  I will check out your change and see if it works for me.

**Comment by ellisch99** [comment]
Tested fine. Thanks for the fix.  I will use your fix instead of mine in case of future updates.
